services:
  web:
    build: .
    command: python quoteshooter/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./quoteshooter/.env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    env_file:
      - ./quoteshooter/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
